Description:  Create Ubuntu Server
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups: 
        - !Ref MyInstanceSecurityGroup
      ImageId: ami-08d4ac5b634553e16
      KeyName: lesson3key
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Udacity

  MyInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0
        