version: '2.1'

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "Run your code here"

  create-infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
        name: Create Infrastructure As Code
        command: |
          aws cloudformation deploy \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --template-file server.yml \
            --region us-east-1

workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws

