version: '2.1'

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "Run your code here"

  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Infrastructure As Code
          command: |
            aws cloudformation deploy \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --template-file server.yml \
              --region us-east-1

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["e4:31:75:0e:cf:31:37:bc:25:8a:74:c8:14:d0:91:7b"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main-remote.yml -i inventory.txt

workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
    #  - create_infrastructure
      - configure_infrastructure
      